# Generated by Django 4.2.2 on 2023-07-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bec',
            fields=[
                ('FW', models.CharField(max_length=100)),
                ('IMEI', models.CharField(max_length=100)),
                ('IMSI', models.CharField(max_length=100)),
                ('ICCID', models.CharField(max_length=100)),
                ('IP', models.CharField(max_length=100, null=True)),
                ('LastConnect', models.CharField(max_length=100)),
                ('MAC', models.CharField(max_length=100)),
                ('MODEL', models.CharField(max_length=100, null=True)),
                ('SYSUPTIME', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('NETWORK', models.CharField(max_length=50, null=True)),
                ('ENB_ID', models.CharField(max_length=50, null=True)),
                ('CELLID', models.CharField(max_length=50, null=True)),
                ('BAND', models.CharField(max_length=50)),
                ('RSSI', models.IntegerField(null=True)),
                ('SINR', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerakiDevice',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('publicIp', models.CharField(max_length=15)),
                ('networkId', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('lastReportedAt', models.DateTimeField()),
                ('model', models.CharField(max_length=100)),
                ('tags', models.JSONField()),
                ('wan1Ip', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('wan1Gateway', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('wan2Ip', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('wan2Gateway', models.CharField(blank=True, default=None, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnifiSite',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lan_health', models.CharField(blank=True, default='unknown', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnifiDevice',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('mac', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('connected_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('provisioned_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('mgmt_network_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('gateway_mac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NOC.merakidevice')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NOC.UnifiSite')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bec', models.ManyToManyField(blank=True, to='NOC.bec')),
                ('meraki_device', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='NOC.merakidevice')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NOC.UnifiSite')),
                ('unifi_device', models.ManyToManyField(to='NOC.unifidevice')),
            ],
        ),
        migrations.AddField(
            model_name='bec',
            name='unifi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NOC.UnifiSite'),
        ),
    ]
