# Generated by Django 4.2.2 on 2023-07-05 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TunnelInterface',
            fields=[
                ('site_name', models.CharField(blank=True, max_length=100, null=True)),
                ('interface', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tunnel_peer_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('tunnel_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('tunnel_mask', models.CharField(blank=True, max_length=15, null=True)),
                ('remote_gateway', models.CharField(blank=True, max_length=15, null=True)),
                ('subscription_ip', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TunnelRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('destination', models.CharField(blank=True, max_length=15, null=True)),
                ('mask', models.CharField(blank=True, max_length=15, null=True)),
                ('vrf', models.CharField(blank=True, max_length=40, null=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtr30.tunnelinterface')),
            ],
        ),
    ]
